# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions."applyMoonPlan"]
  schedule = "0 3 * * *"   # every day at 03:00 UTC
