# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"
functions = "netlify/functions"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions."applyMoonPlan"]
  schedule = "0 3 * * *"   # every day at 03:00 UTC
# netlify.toml
[[redirects]]
from = "https://www.novatradeapp.com/*"
to   = "https://novatradeapp.com/:splat"
status = 301
force = true
