# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

# 1) Canonicalize www to apex FIRST (processed in order)
[[redirects]]
  from = "https://www.novatradeapp.com/*"
  to   = "https://novatradeapp.com/:splat"
  status = 301
  force = true

# 2) SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# 3) Scheduled function (runs daily at 03:00 UTC)
[functions.applyMoonPlan]
  schedule = "0 3 * * *"
